sudo: required
services:
  - docker # Travis to intall docker

before_install:
  - docker build -t jmwashuma/docker-react -f Dockerfile.dev .

script:
  - docker run jmwashuma/docker-react yarn test --coverage=true --watchAll=false
